import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/lib/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Roboto, Montserrat } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '500', '600', '700'], 
  subsets: ['latin',"symbols","greek"],   
  variable: '--font-roboto'  
});

const monsterateUnderline = Montserrat({
  weight: ['400', '500', '600', '700'], 
  subsets: ['latin'], 
  variable: '--font-heading'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${monsterateUnderline.variable}`}>
        <NavBar/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
